title: Windows Apps London
author: Matt Lacey
#email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  WinAppsLdn (Formerly Windows Phone User Group).

show_excerpts: false # set to true to show excerpts on the homepage

logo: /assets/logo.png

# see https://jekyll.github.io/jekyll-seo-tag/usage/
#twitter:
#  username: MRLacey
#  card: summary

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
     twitter: WinAppsLdn
    # github:  MRLacey
     rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: MattRLacey
    # linkedin: MRLacey
    # pinterest: jekyll
    # youtube: MRLacey
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: mrlacey
    #   instance: fosstodon.org
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

defaults:
 -
   scope:
     type: "pages"
   values:
     author: "Matt Lacey"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jemoji
